apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-ms
spec:
  selector:
    matchLabels:
      app: auth-ms
  template:
    metadata:
      labels:
        app: auth-ms
    spec:
      containers:
        - name: auth-ms
          image: auth-ms:latest
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "600Mi"
            requests:
              memory: "300Mi"
          ports:
            - containerPort: 8080
          env:
            - name: JWT_BASE64_URL_ENCODED
              valueFrom:
                secretKeyRef:
                  name: jwt-secrets
                  key: jwt-base64-encode

            - name: NEW_USER_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: user-endpoints
                  key: new-user

            - name: VALIDATE_USER_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: user-endpoints
                  key: validate-user

---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth-ms
  ports:
    - port: 8080
      targetPort: 8080

---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secrets
data:
  # base64 encode of a base64url encoded string
  jwt-base64-encode: U0VsVVNFVlNSVWhQVjFsUFZVUlBTVTVIVkU5RVFWbEpTRTlRUlVWV1JWSlpWRWhKVGtkSlUwZFBUMFE=

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: user-endpoints
data:
  new-user: http://user-service:8080/users/
  validate-user: http://user-service:8080/users/validate
